### ISSUE TITLE
[bug] cycleCount и cycleLimit 

### ISSUE THREAD

**Issue by nett00n** [5mdt/noise#1]
кажется, в использовании cycleCount и cycleLimit баг — каждое третье нажатие на «Play» не срабатывает ожидаемым образом, как в последовательности «Play-Stop-Play-…» (шум не запускается), так и в «Play-Play-Play-…» (шум не изменяется, а выключается)

https://twitter.com/aldragon_net/status/1683381955742646274

**Comment by vorjyga** [comment]
same for me.

Any updates? 🙃

**Comment by nett00n** [comment]
Fixed in https://github.com/5mdt/noise/commit/213587f811fefce0365d3e5bbaf731c1daca8976
